{% set name = "pybloom_live" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d0974d586ec76b58ed218b8b791ea0e71f30e2080437431f7992ae3732a54e4a

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - bitarray >=0.3.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - pybloom_live

about:
  home: https://github.com/joseph-fox/python-bloomfilter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Scalable Bloom Filter implemented in Python

extra:
  recipe-maintainers:
    - roll
